function [ptsc,point_id, ambient, timestamp] = read_blickfeld_csv(dat_name)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: E:\Blickfeld_LiDAR\Samples\test.csv
%
% Auto-generated by MATLAB on 26-Jan-2021 16:24:55

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["X", "Y", "Z", "DISTANCE", "INTENSITY", "POINT_ID", "RETURN_ID", "AMBIENT", "TIMESTAMP"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["X", "Y", "Z", "DISTANCE", "INTENSITY", "POINT_ID", "AMBIENT", "TIMESTAMP"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["X", "Y", "Z", "DISTANCE", "INTENSITY", "POINT_ID", "AMBIENT", "TIMESTAMP"], "ThousandsSeparator", ",");

% Import the data
tabl = readtable(dat_name, opts);

%% Convert to output type
% tabl = table2array(tabl)/correct_factor;
ptsc = pointCloud([tabl.X,tabl.Y, tabl.Z],'Intensity',tabl.INTENSITY,'Color',repmat(tabl.DISTANCE,[1,3]));
point_id =  tabl.POINT_ID;
ambient =  tabl.AMBIENT;
timestamp =  tabl.TIMESTAMP;
%% Clear temporary variables
clear opts


% formatOut = 'dd-mm-yyyy HH:MM:SS';
% timestamp_handle = @(tstamp) datestr(datenum([1970, 1, 1, 0, 0, tstamp]),formatOut);


